server:
  port: 10010
spring:
  application:
    name: sy
  thymeleaf:
    cache: false
    encoding: UTF-8
    mode: HTML5
    prefix: classpath:/templates/
    suffix: .html
  datasource:
    dynamic:
      primary: PRIMARY
      datasource:
        PRIMARY:
          username: root
          password: capslock123
          url: jdbc:mysql://81.70.254.44:3306/shiyu?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
          driver-class-name: com.mysql.jdbc.Driver
  mail:
    host: smtp.mxhichina.com
    username: me@liufei.ltd
    password: yilan980416...
    port: 465
    properties:
      mail:
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
      from: me@liufei.ltd
mybatis-plus:
  mapper-locations: classpath:mappings/*.xml